baseURL = "https://example.com/"
languageCode = "fr"
theme = 'hugo-theme-rfcish'
#Copyright = "&copy; 2025 "
enableEmoji = true
DefaultContentLanguage = "fr"

[params]
favicon = "/img/favicon.ico"
author = "Author"
description = "Clean and simple blog"
ShowThemeInfo = true
toc = false # Default no ToC, declare "toc: true" in post for override

[languages]
  [languages.fr]
    title = "Blog title"
  [languages.fr.params]
    subtitle = "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..."
    languageName = "fr"
    weight = 1
  [languages.en]
    title = "Blog title"
  [languages.en.params]
    subtitle = "sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...."
    languageName = "en"
    weight = 2

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.extensions.extras.delete]
    enable = true
  [markup.goldmark.extensions.extras.insert]
    enable = true
  [markup.goldmark.extensions.extras.mark]
    enable = true
  [markup.goldmark.extensions.extras.subscript]
    enable = true
  [markup.goldmark.extensions.extras.superscript]
    enable = true
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 6 # ToC ends at H6
		ordered = true # generates <ul> instead of <ol>

[pagination]
pagersize = 20

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20
  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30